#docker run  --name elasticsearch -v ~/srv/elas1:/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:5

version: '2.2'

services: 
    elasticsearch: 
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
        container_name: elasticsearch
        environment: 
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        volumes: 
            - ~/srv/elas1:/usr/share/elasticsearch/data
        ports: 
            - 9200:9200
        networks: 
            - esnet
    
networks: 
    esnet:


